# Generated by Django 4.1.7 on 2023-03-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="phone",
            name="image",
            field=models.CharField(max_length=250),
        ),
    ]
